// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdehykfrczmnieleyuiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZWh5a2ZyY3ptbmllbGV5dWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzU3NTEsImV4cCI6MjA3NDU1MTc1MX0.HxBenVCkV1pY-nozhbY9a5unxXI83F4kjZw3hvIjD-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});